# This file was generated by GoReleaser. DO NOT EDIT.
cask "backup-github" do
  version "0.3.5"

  on_macos do
    on_arm do
      sha256 "348388943d4f28bcca80543b2302b42c51de406bc1122b725d71f0e01d3fa150"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_arm64.zip"
    end
    on_intel do
      sha256 "38b6a84ca964e953c762346e172b916b6f9bd92be9a3bb06197d974ca9d608ed"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_x86_64.zip"
    end
  end

  name "backup-github"
  desc "A simple CLI utility, written in GoLang, to backup all of your GitHub repos."
  homepage "https://github.com/ChrisWiegman/backup-github"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backup-github"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backup-github"]
    end
  end

  # No zap stanza required
end
