# This file was generated by GoReleaser. DO NOT EDIT.
cask "backup-github" do
  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "d00ea0df6d4bca9a59be1bbdaf350e8825d65da62ba600a45912f8191fcde982"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_arm64.zip"
    end
    on_intel do
      sha256 "dcdd69d0d374d18a2d07dc8e467979370edb6757d55ab5adb9ce296f3ba2d2bc"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_x86_64.zip"
    end
  end

  name "backup-github"
  desc "A simple CLI utility, written in GoLang, to backup all of your GitHub repos."
  homepage "https://github.com/ChrisWiegman/backup-github"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backup-github"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backup-github"]
    end
  end

  # No zap stanza required
end
