# This file was generated by GoReleaser. DO NOT EDIT.
cask "backup-github" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "89d5acf29dec61de808e013dd0c8efb58aaa93446122f81fc8cb451b462a7df5"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_x86_64.zip"
    end
    on_arm do
      sha256 "8d4c5db6868260c6c14d319d281c4c961e73107602b65bb112f74dd75d68f47a"
      url "https://github.com/ChrisWiegman/backup-github/releases/download/#{version}/backup-github_macos_arm64.zip"
    end
  end

  name "backup-github"
  desc "A simple CLI utility, written in GoLang, to backup all of your GitHub repos."
  homepage "https://github.com/ChrisWiegman/backup-github"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backup-github"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backup-github"]
    end
  end

  # No zap stanza required

end
